### ISSUE TITLE
Error "group map is already registered" in Kubernetes 1.6.0

### ISSUE THREAD

**Issue by everett-toews** [ContainerSolutions/registry-tooling#7] opened 2017-04-05 22:54 UTC
To reproduce the error

```bash
$ minikube start --kubernetes-version 1.6.0
...

$ ./reg-tool.sh install-k8s-reg
...

$ kubectl get pods --show-all
NAME                                                    READY     STATUS             RESTARTS   AGE
copy-certs-497761da-1a50-11e7-a9d0-080027dc1105-1wlgn   0/1       CrashLoopBackOff   3          1m
create-certs-3s3m3                                      0/1       Completed          0          1m

$ kubectl logs copy-certs-497761da-1a50-11e7-a9d0-080027dc1105-1wlgn
copying certs
error: group map[apps:0xc82038eb60 autoscaling:0xc82038ec40 batch:0xc82038ecb0 extensions:0xc82038ed90 policy:0xc82038ee00 rbac.authorization.k8s.io:0xc82038ee70 :0xc82038eaf0 authorization.k8s.io:0xc82038ebd0 componentconfig:0xc82038ed20 authentication.k8s.io:0xc82038ef50 federation:0xc82038ea80] is already registered
```

Versions

```bash
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.1", GitCommit:"b0b7a323cc5a4a2019b2e9520c21c7830b7f708e", GitTreeState:"clean", BuildDate:"2017-04-03T23:37:53Z", GoVersion:"go1.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.0", GitCommit:"fff5156092b56e6bd60fff75aad4dc9de6b6ef37", GitTreeState:"dirty", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"go1.7", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by Uditmittal** [comment] 2017-04-28 11:57
kubectl run hello-minikube --image=gcr.io/google_containers/echoserver:1.4 --port=8080


error: group map[authorization.k8s.io:0xc8203db030 autoscaling:0xc8203db0a0 storage.k8s.io:0xc8202f01c0 :0xc8203dae00 authentication.k8s.io:0xc8203daee0 batch:0xc8203db260 certificates.k8s.io:0xc8203db2d0 componentconfig:0xc8203db340 extensions:0xc8202f0070 policy:0xc8202f00e0 rbac.authorization.k8s.io:0xc8202f0150 federation:0xc8203da930 apps:0xc8203dae70] is already registered

 kubectl run 
hello-minikube --image=gcr.io/google_containers/echoserver:1.4 --port=8080
error: group map[authorization.k8s.io:0xc8203db030 autoscaling:0xc8203db0a0 storage.k8s.io:0xc8202f01c0 :0xc8203dae00 authentication.k8s.io:0xc8203daee0 batch:0xc8203db260 certificates.k8s.io:0xc8203db2d0 componentconfig:0xc8203db340 extensions:0xc8202f0070 policy:0xc8202f00e0 rbac.authorization.k8s.io:0xc8202f0150 federation:0xc8203da930 apps:0xc8203dae70] is already registered

**Comment by ggarnier** [comment] 2017-05-04 19:09
I had this same issue after updating minikube. I was using an older version of kubectl. I fixed it installing the latest version of kubectl via curl (https://kubernetes.io/docs/tasks/kubectl/install/) - Homebrew didn't have the latest version.

**Comment by amouat** [comment] 2017-05-25 16:12
This is now fixed. It was caused by old version of kubectl in the Dockerfiles.

**Closed by amouat** 2017-05-25 16:12 UTC

**Comment by ArunGayu** [comment] 2017-06-11 07:37
I am getting the same error when i try executing kubectl get nodes. Below is the error message. Could you please help?

error: group map[storage.k8s.io:0xc8203f03f0 federation:0xc8203397a0 :0xc820339c70 apps:0xc820339ce0 certificates.k8s.io:0xc8203f0150 componentconfig:0xc8203f01c0 extensions:0xc8203f02a0 rbac.authorization.k8s.io:0xc8203f0380 authentication.k8s.io:0xc820339d50 authorization.k8s.io:0xc820339ea0 autoscaling:0xc820339f10 batch:0xc8203f00e0 policy:0xc8203f0310] is already registered

**Comment by amouat** [comment] 2017-06-11 12:07
If you found this issue via Google, please note that this is *not* the Kubernetes repo. Please go there (https://github.com/kubernetes/kubernetes) to report Kubernetes issues. Only use this repo for problems with the registry-tooling project.

However, the problem/solution is simple - you need to use a version of kubectl binary that is compatible with your Kubernetes cluster. Most probably you just need to download a newer version.
